# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 279ed05cbee38b0956fc52519a1799ded56f7ed05b465349dcf60d511ebe1a287d17c01b45844ebde1d8b4b2ce22d4ed8c2d42b74c873bab3a64bc0ae1a5388c

test:
  secret_key_base: 0e3024bd9e51b630703b55a502048fc0d89ed90f5e4906c5f34c903430c1bba7872428fedb724986b838f0e0efd2118b6545f70f8ad738b26f8bb65b0c476788

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
